modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "GNU GPLv3"

[[mods]]
modId = "ckinvsee"
version = "${version}"
displayName = "CK Inv See"
authors = "KoromaruKoruko, CanadianBaconBoi"
description = '''
Allows you to see offline + online players inventories + echests
'''
#logoFile = ""

[[dependencies.ckinvsee]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ckinvsee]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ckinvsee]]
modId = "architectury"
mandatory = true
versionRange = "[4.11.91,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ckinvsee]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ckinvsee]]
modId = "luckperms"
mandatory = false
versionRange = "[5.4,)"
ordering = "AFTER"
side = "SERVER"