name: Crossplatform Build

on:
  release:
    types: [created]
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.7.0
      with:
        arguments: build
    
    - name: Upload Forge jar
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Forge
        path: forge/build/libs/*-[0-9].[0-9].[0-9].jar
        if-no-files-found: error 
        retention-days: 90
        
    - name: Upload Fabric jar
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Fabric
        path: fabric/build/libs/*-[0-9].[0-9].[0-9].jar
        if-no-files-found: error 
        retention-days: 90
        
    - name: Upload Quilt jar
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Quilt
        path: quilt/build/libs/*-[0-9].[0-9].[0-9].jar
        if-no-files-found: error 
        retention-days: 90
